# Generated by Django 5.0.2 on 2024-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='blood_oxygen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
